# Generated by Django 4.1.5 on 2023-04-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.FileField(null=True, upload_to='message_attachments/'),
        ),
    ]
