# Generated by Django 4.1.7 on 2023-04-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_message_encrypted_key_message_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='encrypted_key',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='message',
            name='iv',
            field=models.BinaryField(default=b''),
        ),
    ]
