# Generated by Django 4.1.7 on 2023-04-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_alter_message_encrypted_key_alter_message_iv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encrypted_key',
        ),
        migrations.RemoveField(
            model_name='message',
            name='iv',
        ),
    ]
