# Generated by Django 4.1.7 on 2023-04-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_privatekey_publickey_message_private_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='encrypted_key',
            new_name='encrypted_message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='iv',
            new_name='signature',
        ),
        migrations.RemoveField(
            model_name='message',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='message',
            name='public_key',
        ),
    ]
