# Generated by Django 4.1.7 on 2023-04-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_rename_encrypted_key_message_encrypted_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient_public_key',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_private_key',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
