# Generated by Django 4.1.7 on 2023-04-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_message_recipient_public_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateKey',
        ),
        migrations.DeleteModel(
            name='PublicKey',
        ),
        migrations.RemoveField(
            model_name='message',
            name='encrypted_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient_public_key',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_private_key',
        ),
        migrations.RemoveField(
            model_name='message',
            name='signature',
        ),
    ]
