# Generated by Django 4.0.3 on 2022-04-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_user', '0004_alter_main_user_id_alter_main_user_user'),
        ('post', '0002_remove_post_title_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_user.main_user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_user.main_user'),
        ),
    ]
