# Generated by Django 4.0.3 on 2022-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_photos_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.FileField(blank=True, upload_to='post/post_images'),
        ),
    ]
