# Generated by Django 4.1.7 on 2023-04-13 05:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('anonymouschat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.FileField(null=True, upload_to='message_attachments/')),
            ],
        ),
    ]
