# Generated by Django 4.1.7 on 2023-04-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymouschat', '0002_anonymousmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousmessage',
            name='room_id',
            field=models.CharField(max_length=200),
        ),
    ]
