# Generated by Django 4.1.7 on 2023-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymouschat', '0003_alter_anonymousmessage_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousmessage',
            name='senderIp',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
