# Generated by Django 4.1.7 on 2023-04-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymouschat', '0004_anonymousmessage_senderip'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouschatroom',
            name='users',
            field=models.JSONField(default=list),
        ),
    ]
