# Generated by Django 4.0.4 on 2022-05-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_user', '0006_alter_main_user_user_delete_user'),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='given_user_s_friend', to='main_user.main_user'),
            preserve_default=False,
        ),
    ]
