# Generated by Django 4.0.3 on 2022-04-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_user',
            name='profile_image',
            field=models.ImageField(default='a', upload_to='media'),
            preserve_default=False,
        ),
    ]
