# Generated by Django 4.0.3 on 2022-04-10 07:49

from django.conf import settings
from django.db import migrations, models
import main_user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_user', '0003_alter_main_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='main_user',
            name='user',
            field=models.OneToOneField(on_delete=main_user.models.Main_user.delete_user, to=settings.AUTH_USER_MODEL),
        ),
    ]
