# Generated by Django 4.1.5 on 2023-03-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='connected_profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='connected_profiles',
            field=models.JSONField(null=True),
        ),
    ]
