# Generated by Django 4.1.5 on 2023-03-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x0000027421B58040>', editable=False, primary_key=True, serialize=False),
        ),
    ]
