# Generated by Django 4.1.5 on 2023-03-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_connected_profiles_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='connected_profiles',
            field=models.JSONField(default=list),
        ),
    ]
