# Generated by Django 4.1.5 on 2023-04-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_connectionrequest_reciever_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
