# Generated by Django 4.1.5 on 2023-04-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_connectionrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
