# Generated by Django 4.1.5 on 2023-04-01 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_connectionrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
